name: 'Install Dependencies'
description: Install pip dependencies
inputs: {}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        fetch-depth: 0
    - name: Install dependencies
      shell: bash
      run: |
        ls
        echo "Installing all required dependencies"
